backend:
  name: git-gateway
  branch: main

media_folder: images/uploads

collections:
  - name: noticias
    label: Noticias
    folder: _noticias
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Categoría, name: cat, widget: string}
      - {label: Título, name: titulo, widget: string}
      - {label: Emoji, name: emoji, widget: string, default: "⚽"}
      - {label: Fecha, name: fecha, widget: string}
      - {label: Contenido, name: body, widget: markdown}
